# Crane-based derivation for the loku-web binary.
# Called from flake.nix with: import ./web.nix { inherit craneLib commonArgs pkgs; }
#
# The package output includes:
#   $out/bin/loku-web                 — the server binary
#   $out/share/loku-web/frontend/     — compiled Elm frontend assets
#
# The NixOS module passes --frontend-path pointing at the share directory.
#
# Elm build: uses pkgs.elmPackages.fetchElmDeps with the elm-srcs.nix and
# registry.dat files generated by elm2nix.  All package fetching happens
# through individual fixed-output derivations (one per package, each with
# its own hash), so the build is fully offline and hermetic.  No blobs in
# the repository.
#
# When elm.json dependency versions change, regenerate both files:
#   cd frontend
#   nix run 'github:NixOS/nixpkgs/25.11#elm2nix' -- convert 2>/dev/null > elm-srcs.nix
#   nix run 'github:NixOS/nixpkgs/25.11#elm2nix' -- snapshot
# then commit elm-srcs.nix and registry.dat.
{ craneLib, commonArgs, pkgs }:
let
  elmFrontend = pkgs.stdenv.mkDerivation {
    name = "loku-elm-frontend";
    src = ../../frontend;
    nativeBuildInputs = [ pkgs.elmPackages.elm ];

    configurePhase = pkgs.elmPackages.fetchElmDeps {
      elmPackages = import ../../frontend/elm-srcs.nix;
      elmVersion = "0.19.1";
      registryDat = ../../frontend/registry.dat;
    };

    buildPhase = ''
      elm make src/Main.elm --optimize --output elm.js
    '';

    installPhase = ''
      mkdir -p $out
      cp elm.js $out/
      cp public/index.html $out/
    '';
  };

  binary = craneLib.buildPackage (commonArgs // {
    pname = "loku-web";
    cargoExtraArgs = "-p loku-web";
  });
in
pkgs.symlinkJoin {
  name = "loku-web";
  paths = [ binary ];
  postBuild = ''
    mkdir -p $out/share/loku-web
    ln -s ${elmFrontend} $out/share/loku-web/frontend
  '';
}
